config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minmum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    validates :username, presence: true,  uniqueness: {case_sensitive: false},length: {minimum:3,maximum:25}
    EMAIL_VALIDATION_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum:35}, format: {with: EMAIL_VALIDATION_REGEX}
    has_many :articles , dependent: :destroy

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        if session[:user_id] 
            @current_user ||= User.find(session[:user_id])
        end
    end

    def logged_in?
        !!current_user #current user is present or not, that will be returened in boolean form using !!
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [ :show, :index ]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        sendArticleCreatedMail(@article)
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def sendArticleCreatedMail(article)
    # WelcomeMailer.send_welcome_mail(article).deliver_now
  end


  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index , :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category Created Succesfully"
            redirect_to @category
        else
            render 'new'
        end
    end

    private 
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "ONly admin will perform that action"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        # redirect_to articles_path if logged_in?
    end

    def about
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        puts "here"
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id 
            flash[:notice] = "Logged in successfully"   
            redirect_to articles_path
        else
            flash[:alert] = "Invalid email/password combination"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user , only: [:show, :edit , :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update , :destroy]
    
    def new
       @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to Blog, Sign Up successfull for #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit 
        if @user
            
        end
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "your account was updated"
            redirect_to user_path
        else
            return 'edit'
        end
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        flash[:notice] = "User deleted: " + @user.username
        if @user.destroy
            session[:user_id] = nil
            redirect_to root_path
        end
        
    end
    
    private 
    def user_params
        params.require(:user).permit(:username,:email,:password)
    end

    
    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        byebug
        if current_user != @user
          flash[:alert] = "You can only edit your own account"
          redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user,options = {size: 80})
        emailAddress = user.email.downcase 
        hash = Digest::MD5.hexdigest(emailAddress)
        size = options[:size]
        gravatarUrl = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatarUrl, alt: user.username)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

<p>
    <% if article.user %>
    <strong>by:</strong>
    <%= article.user.username %>
  </p>
  <% end%>
</div>

app/views/articles/_form.html.erb
<% if @article.errors.any?%>
<h2>The following errors prevented the article from being saved</h2>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
    <% end %>
</ul>
<% end %>
<%= form_with(model: @article,local: true) do |f|%>
<p>
    <%= f.label :title%><br>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :description%><br>
    <%= f.text_area :description %>
</p>

<p>
    <%= f.submit %>
</p>
<%end%>

app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= render 'form' %>

<%=  link_to 'Cancel Edit', articles_path %>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>  ||  
      <% if logged_in? && article.user == current_user %>
      <%= link_to "Edit this article", edit_article_path(article) %>
      <% end %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>
<br>
<%=  link_to 'Back to Home', articles_path %>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
<% if logged_in? && @article.user == current_user %>
  <%= link_to "Edit this article", edit_article_path(@article) %>
  <%= button_to "Destroy this article", @article, method: :delete %>
<% end %>  ||
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/categories/index.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>


<h3>Categories </h3>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>
  <% @categories.each do |category| %>
    Category Name: <%= category.name %>
    <p>
      <%= link_to "Show this category", category_path(category) %>
    </p>
  <% end %>
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1>create category </h1>

  <% if @category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with(model: @category) do |form| %>

  <div>
    <%= form.label :name, 'Category Name',style: "display: block" %>
    <%= form.text_field :name, placeholder: "Enter a category" %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

Category Name: <%= @category.name %>

app/views/layouts/_messages.html.erb
  <% flash.each do |name,msg| %>
   <%=msg%>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DetailingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/home.html.erb
<h1>This is home page</h1>
<%= link_to "Sign up!", signup_path %>
<%= link_to "Bloggers", users_path %>
<%= link_to "Articles", articles_path %>
<% if current_user && current_user.admin?%>
    Profile [<%=current_user.username%>]
    || <%= link_to "create new category", new_category_path%>
<% end %>
<%= link_to "view categories", categories_path%>
<% if logged_in? %>
<%= button_to 'Delete User', user_path(current_user), method: :delete, data: {confirm: "Are you share" } %>
<%= button_to 'Logout', logout_path, method: :delete %>
<%else%>
<%= link_to "Log in", login_path %>
<%end%>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with(model: @user) do |form| %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, placeholder: "Enter a username" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, placeholder: "Enter your email address" %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, placeholder: "Choose a password" %>
  </div>

  <div>
    <%= form.submit(@user.new_record? ? "Sign Up" : "Update Account") %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>String:</strong>
    <%= user.string %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Edit Profile </h1>

<%= render "form"%>

app/views/users/index.html.erb
<h1>All the Bloggers are here </h1>

<div id="users">
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
  <% @users.each do |user| %>
    <p>
      <%= link_to user.username, user %>
      <%= link_to gravatar_for(user,size: 150), user %>
      <%= pluralize(user.articles.count, "article")%>
      <%if logged_in? and user == current_user %>
      <%= link_to "edit User", edit_user_path(user) %>
      <%end%>

<% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user)%>
              <% end %>
              <% if current_user.admin? %>
                <%= button_to 'Delete User', user_path(current_user), method: :delete, data: {confirm: "Are you share" } %>
              <% end %>
              <% end %>

      <%= link_to "View profile", user %>
      <small><%= time_ago_in_words(user.created_at)%></small>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1>sign up </h1>

<%= render "form"%>

app/views/users/show.html.erb
<%= flash[:notice] %>

<h1><%=  @user.username %> Profile </h1>
<%= gravatar_for @user, size: 200%>

<h3><%=  @user.username %> Articles </h3>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<% if logged_in? and @user == current_user %>
<%= link_to "Edit your profile", edit_user_path(@user)%>
<% end %>
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>